# Generated by Django 5.0.14 on 2025-04-30 17:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('total_presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='Conceptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='Registrar_Presupuesto.categoria')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_limite', models.DateField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.categoria')),
                ('Conceptos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.conceptos')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo', models.TextField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.bancos')),
                ('presupuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Registrar_Presupuesto.presupuesto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.responsables')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.bancos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.categoria')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.conceptos')),
                ('presupuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Registrar_Presupuesto.presupuesto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.responsables')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_de_pago', models.DateField(default=datetime.date.today)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Registrar_Presupuesto.categoria')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Registrar_Presupuesto.conceptos')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Registrar_Presupuesto.presupuesto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Registrar_Presupuesto.responsables')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalles de Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.bancos')),
                ('presupuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='Registrar_Presupuesto.presupuesto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.responsables')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
            },
        ),
    ]
