# Generated by Django 5.0.14 on 2025-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
