# Generated by Django 5.0.14 on 2025-04-05 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0002_responsables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancos',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='conceptos',
            options={'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.AlterModelOptions(
            name='detallepresupuesto',
            options={'verbose_name': 'Detalle de Presupuesto', 'verbose_name_plural': 'Detalles de Presupuesto'},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='responsables',
            options={'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsables'},
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
