# Generated by Django 5.0.14 on 2025-04-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0003_alter_bancos_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='fecha',
            new_name='mes',
        ),
    ]
