# Generated by Django 5.0.14 on 2025-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0004_rename_fecha_presupuesto_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
