# Generated by Django 5.0.14 on 2025-04-08 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0005_bancos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuesto',
            name='Responsables',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Registrar_Presupuesto.responsables'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Registrar_Presupuesto.categoria'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
