# Generated by Django 5.0.14 on 2025-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0006_detallepresupuesto_responsables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='total_presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
