# Generated by Django 5.0.14 on 2025-04-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0007_presupuesto_total_presupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepresupuesto',
            old_name='Responsables',
            new_name='responsable',
        ),
    ]
