# Generated by Django 5.0.14 on 2025-04-09 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0008_rename_responsables_detallepresupuesto_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.bancos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.categoria')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.conceptos')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.responsables')),
            ],
        ),
    ]
