# Generated by Django 5.0.14 on 2025-04-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0009_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='gasto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
