# Generated by Django 5.0.14 on 2025-04-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0010_alter_gasto_options_remove_gasto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='presupuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Registrar_Presupuesto.presupuesto'),
        ),
    ]
