# Generated by Django 5.0.14 on 2025-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0011_gasto_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
