# Generated by Django 5.0.14 on 2025-04-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0013_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.bancos')),
                ('presupuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='Registrar_Presupuesto.presupuesto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.responsables')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
            },
        ),
    ]
