# Generated by Django 5.0.14 on 2025-04-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar_Presupuesto', '0014_saldos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_limite', models.DateField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.categoria')),
                ('Conceptos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrar_Presupuesto.conceptos')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
